repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: check-json

-   repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
    -   id: dead

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
-   repo: https://github.com/miki725/importanize/
    rev: 'master'
    hooks:
    - id: importanize
      args: [--verbose]



